version: '3'

services:
  consul-service-master:
    image: consul:1.3.0
    hostname: consul-service-master
    ports:
      - 28500:8500
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul-service-1:
    image: consul:1.3.0
    hostname: consul-service-1
    command: "agent -server -retry-join consul-service-master -client 0.0.0.0"

  consul-service-2:
    image: consul:1.3.0
    hostname: consul-service-2
    command: "agent -server -retry-join consul-service-master -client 0.0.0.0"

  consul-agent-1:
    image: consul:1.3.0
    hostname: consul-agent-1
    command: "agent -retry-join consul-service-master -client 0.0.0.0"

  consul-agent-2:
    image: consul:1.3.0
    hostname: consul-agent-2
    command: "agent -retry-join consul-service-master -client 0.0.0.0"

networks:
  default:
    external:
      name: local-network
